config/routes.rb
Wingman::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :beta_emails, :bars

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
      resources :sessions 
      resources :bars 
      resources :locations 
    end
  end

end

app/models/bar.rb
# == Schema Information
#
# Table name: bars
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  yelp_id       :string(255)
#  logo_url      :string(255)
#  image_url     :string(255)
#  lat           :decimal(10, 6)
#  lon           :decimal(10, 6)
#  review_count  :integer
#  rating        :decimal(4, 2)
#  current_users :integer
#  price         :decimal(4, 2)
#  created_at    :datetime
#  updated_at    :datetime
#  phone_number  :string(255)
#  address       :string(255)
#  city          :string(255)
#  state         :string(255)
#  neighborhood  :string(255)
#  category      :string(255)
#

class Bar < ActiveRecord::Base
  geocoded_by :address, :latitude  => :lat, :longitude => :lon 
  after_validation :geocode
  
  has_many :events

  def current_users
    Event.where('bar_id = ? AND updated_at > ?', id, Time.now - 15.minutes).count
  end
end

app/controllers/api/v1/bars_controller.rb
module Api
  module V1
    class BarsController < ApplicationController
      # acts_as_token_authentication_handler_for User
      respond_to :json
      
      def index
        # hash = {:id => params[:id], :lat => params[:lat], :lon => params[:lon]}
        # respond_with Bar.all.limit(20)
        respond_with Bar.near([params[:lat],params[:lon]], 20).limit(20).to_json(:methods => :current_users)
      end
      
      def show
        respond_with Bar.find(params[:id])
      end
    end
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def new
    @bar = Bar.new
  end

  def index
    @bars = Bar.all
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
      flash[:notice] = @bar.name + " has been added as an Bar!"
      redirect_to @bar
    else
      render 'new'
    end
  end

  def destroy
    Bar.find(params[:id]).destroy
    flash[:success] = "Bar deleted."
    redirect_to bars_path
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def update
    @bar = Bar.find(params[:id])
    if @bar.update_attributes(bar_params)
      flash[:notice] = "Bar profile updated"
      redirect_to @bar
    else
      render 'edit'
    end
  end

  def show
    @bar = Bar.find(params[:id])
  end

  private

    def bar_params
      params.require(:bar).permit(:name, :logo_url, :image_url, :rating, :drink_price, :phone_number, :address, :description, :schedule, :food, :music, :category)
    end
end

app/views/bars/edit.html.haml
= stylesheet_link_tag 'custom', :media => "all"
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li
        %a{:href => bars_path} All Bars
      %li
        %a{:href => new_bar_path} New Bar
    %h3.text-muted Edit Bar
  .row.marketing
    .container
      .col-md-12.centerForm
        = form_for(@bar) do |f|
          = render 'shared/error_messages', object: f.object
          .form-horizontal
            .form-group
              .col-sm-4.control-label= f.label :name
              .col-sm-8= f.text_field :name, :class => "form-control", :placeholder => "e.g. Joe's Pub"
            .form-group
              .col-sm-4.control-label= f.label :logo_url
              .col-sm-8= f.text_field :logo_url, :class => "form-control", :placeholder => "bar's logo should be around (300 x 300)"
            .form-group
              .col-sm-4.control-label= f.label :image_url
              .col-sm-8= f.text_field :image_url, :class => "form-control", :placeholder => "header image should be around (800 x 400)"
            .form-group
              .col-sm-4.control-label= f.label :rating
              .col-sm-8= f.number_field :rating, step: 0.5, :class => "form-control", :placeholder => "out of 5 (e.g. 4.5)"
            .form-group
              .col-sm-4.control-label= f.label :drink_price
              .col-sm-8= f.number_field :drink_price, step: 0.01, :class => "form-control", :placeholder => "average price of a drink."
            .form-group
              .col-sm-4.control-label= f.label :phone_number
              .col-sm-8= f.text_field :phone_number, :class => "form-control", :placeholder => "optional"
            .form-group
              .col-sm-4.control-label= f.label :address
              .col-sm-8= f.text_field :address, :class => "form-control", :placeholder => "e.g. 1232 Main St. Chicago, IL"
            .form-group
              .col-sm-4.control-label= f.label :category
              .col-sm-8
                = f.select :category, options_for_select(%w[champagne_bars divebars gaybars college_bars lounges pubs sportsbars wine_bars nightclubs]), { include_blank: false }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :description
              .col-sm-8= f.text_area :description, :class => "form-control", :placeholder => "Short description of the bar."
            .form-group
              .col-sm-4.control-label= f.label :music
              .col-sm-8
                = f.select :music, options_for_select(%w[hip_hop rock oldies dance electronic dj live jazz]), { include_blank: true }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :food
              .col-sm-8
                = f.select :food, options_for_select(%w[burgers finger steak seafood mexican italian]), { include_blank: true }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :schedule
              .col-sm-8= f.text_area :schedule, :class => "form-control", :placeholder => "schedule for upcoming entertainment."
            .form-group
              .col-sm-offset-4.col-sm-8
                = f.submit "Edit Bar", class: "btn btn-default"
  .footer
    %p © WingMan 2014

app/views/bars/index.html.haml
= stylesheet_link_tag 'custom', :media => "all"
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li.active
        %a{:href => bars_path} All Bars
      %li
        %a{:href => new_bar_path} New Bar
    %h3.text-muted All Bars
  .row.marketing
    .container
      %table.table.table-hover
        %thead
          %tr
            %th Name
            %th Rating
            %th People There
            %th Address
        %tbody
        - @bars.each do |bar|
          %tr
            %td
              = link_to bar.name, bar
            %td
              = bar.rating.to_s
            %td
              = bar.current_users.to_s
            %td
              = bar.address
  .footer
    %p © WingMan 2014

app/views/bars/new.html.haml
= stylesheet_link_tag 'custom', :media => "all"
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li
        %a{:href => bars_path} All Bars
      %li.active
        %a{:href => new_bar_path} New Bar
    %h3.text-muted Add Bar
  .row.marketing
    .container
      .col-md-12.centerForm
        = form_for(@bar) do |f|
          = render 'shared/error_messages', object: f.object
          .form-horizontal
            .form-group
              .col-sm-4.control-label= f.label :name
              .col-sm-8= f.text_field :name, :class => "form-control", :placeholder => "e.g. Joe's Pub"
            .form-group
              .col-sm-4.control-label= f.label :logo_url
              .col-sm-8= f.text_field :logo_url, :class => "form-control", :placeholder => "bar's logo should be around (300 x 300)"
            .form-group
              .col-sm-4.control-label= f.label :image_url
              .col-sm-8= f.text_field :image_url, :class => "form-control", :placeholder => "header image should be around (800 x 400)"
            .form-group
              .col-sm-4.control-label= f.label :rating
              .col-sm-8= f.number_field :rating, step: 0.5, :class => "form-control", :placeholder => "out of 5 (e.g. 4.5)"
            .form-group
              .col-sm-4.control-label= f.label :drink_price
              .col-sm-8= f.number_field :drink_price, step: 0.01, :class => "form-control", :placeholder => "average price of a drink ($)"
            .form-group
              .col-sm-4.control-label= f.label :phone_number
              .col-sm-8= f.text_field :phone_number, :class => "form-control", :placeholder => "optional"
            .form-group
              .col-sm-4.control-label= f.label :address
              .col-sm-8= f.text_field :address, :class => "form-control", :placeholder => "e.g. 1232 Main St. Chicago, IL"
            .form-group
              .col-sm-4.control-label= f.label :category
              .col-sm-8
                = f.select :category, options_for_select(%w[divebars gaybars college_bars lounges pubs sportsbars wine_bars nightclubs]), { include_blank: false }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :description
              .col-sm-8= f.text_area :description, :class => "form-control", :placeholder => "Short description of the bar."
            .form-group
              .col-sm-4.control-label= f.label :music
              .col-sm-8
                = f.select :music, options_for_select(%w[hip_hop rock oldies dance electronic dj live jazz]), { include_blank: true }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :food, "Food (blank for none)"
              .col-sm-8
                = f.select :food, options_for_select(%w[burgers finger steak seafood mexican italian]), { include_blank: true }, :class => "form-control"
            .form-group
              .col-sm-4.control-label= f.label :schedule
              .col-sm-8= f.text_area :schedule, :class => "form-control", :placeholder => "schedule for upcoming entertainment."
            .form-group
              .col-sm-offset-4.col-sm-8
                = f.submit "Create Bar", class: "btn btn-default"
  .footer
    %p © WingMan 2014

app/views/bars/show.html.haml
= stylesheet_link_tag 'custom', :media => "all"
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li
        %a{:href => bars_path} All Bars
      %li
        %a{:href => new_bar_path} New Bar
    %h3.text-muted= @bar.name
  .row.marketing
    .container
      .col-md-4
        %img.logo_image{:src => @bar.logo_url}
        %br/
        %br/
        = link_to "Edit", edit_bar_path(@bar), :class => "btn btn-primary"
        = link_to "Delete", @bar, method: :delete, data: { confirm: "You sure?" }, title: @bar.name, :class => "btn btn-danger"
        %br/
        %br/
        = @bar.lat.to_s + ", " + @bar.lon.to_s
      .col-md-8
        %img.header_image{:src => @bar.image_url}
        %br/
        %br/
        = @bar.address
        %br/
        = @bar.phone_number
        %br/
        = "Rating: " + @bar.rating.to_s
        %br/
        = "Price: " + @bar.price.to_s
        %br/
        = @bar.category
        
  .footer
    %p © WingMan 2014